services:
  atlas:
    image: atlas
    ports:
      - 81:80
    environment:
      - USE_DYNAMIC_WEBAPI_URL=false
      - WEBAPI_URL=https://localhost:8080/WebAPI/
      - ATLAS_SECURITY_DB_PROVIDER_ENABLED=true
    depends_on:
      - webapi
  webapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/ohdsi
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_OHDSI_SCHEMA=webapi
      - FLYWAY_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ohdsi
      - FLYWAY_DATASOURCE_USERNAME=postgres
      - FLYWAY_DATASOURCE_PASSWORD=postgres
      - FLYWAY_SCHEMAS=webapi
      - FLYWAY_PLACEHOLDERS_OHDSISCHEMA=webapi
      - SPRING_BATCH_REPOSITORY_TABLEPREFIX=webapi.BATCH_
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=webapi
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ohdsi